name: DKIM Snapshots

on:
  workflow_dispatch:

jobs:
  dkim-snapshots:
    permissions:
      id-token: write
      contents: write
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Perform DKIM Snapshots
        run: |
          mkdir -p results
          while IFS=: read -r domain selector || [ -n "$domain" ]; do
            file="results/${selector}._domainkey.${domain}.txt"
            record=$(dig +short txt "${selector}._domainkey.${domain}")
            echo "$record" > "$file"
          done < selectors.txt
          
      - name: Create release
        run: |
          dtstr=$(date -u +'%Y-%m-%d-%H-%M-%S')
          tar -czf results.tar.gz results/
          gh release create "snapshot-$dtstr" results.tar.gz \
            --title "DKIM Snapshots - $dtstr" \
            --notes "Automated snapshot release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate build provenance attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: results.tar.gz
